# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('state', django_fsm.FSMField(db_index=True, default=b'pending', max_length=50)),
                ('is_article', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.URLField()),
                ('state', django_fsm.FSMField(db_index=True, default=b'pending', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='allurl',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', related_query_name=b'url', to='cortex.Source'),
        ),
    ]
