# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('domain_name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('links', models.CharField(max_length=255)),
                ('parse_time', models.CharField(max_length=255)),
                ('html', models.TextField()),
                ('publish_date', models.DateField()),
                ('state', django_fsm.FSMField(db_index=True, default=b'pending', max_length=50)),
            ],
        ),
    ]
