# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='trusted_source',
            field=models.BooleanField(default=False),
        ),
    ]
