# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0003_source_trusted_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='processed_spider',
            field=models.BooleanField(default=False, verbose_name=b'Whether processed by spider'),
        ),
    ]
