# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0003_source_trusted_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='html',
        ),
        migrations.AddField(
            model_name='allurl',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='allurl',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', related_query_name='url', to='cortex.Source'),
        ),
        migrations.AlterField(
            model_name='allurl',
            name='state',
            field=django_fsm.FSMField(db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='state',
            field=django_fsm.FSMField(db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='state',
            field=django_fsm.FSMField(db_index=True, default='pending', max_length=50),
        ),
    ]
