# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0004_auto_20160911_1450'),
        ('cortex', '0004_auto_20160916_0812'),
    ]

    operations = [
    ]
