# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
